# Generated by Django 5.1 on 2024-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.IntegerField(),
        ),
    ]
